from django.urls import path
from . import views
from . import api_platform as platform_api
from . import api_public as public_api
from . import client_requests as cr
from . import workspace_access as wsa
from . import system_testing as st
from . import system_testing_share as st_share
from . import handbook as hb
from . import awa_api as awa
from . import management_api as mgmt
from . import github_views
from . import pricing_api
from . import projects_api as projects
from . import sites_api as sites

urlpatterns = [
    # ── Sentinel platform modules: domains, repositories ──
    path('api/domains', platform_api.api_domains, name='api_domains'),
    path('api/domains/create', platform_api.api_domain_create, name='api_domain_create'),
    path('api/domains/<int:pk>', platform_api.api_domain_update, name='api_domain_update'),
    path('api/domains/<int:pk>/delete', platform_api.api_domain_delete, name='api_domain_delete'),

    path('api/repos', platform_api.api_repos, name='api_repos'),
    path('api/repos/create', platform_api.api_repo_create, name='api_repo_create'),
    path('api/repos/<int:pk>', platform_api.api_repo_update, name='api_repo_update'),
    path('api/repos/<int:pk>/delete', platform_api.api_repo_delete, name='api_repo_delete'),
    path('api/repos/<int:pk>/history', platform_api.api_repo_history, name='api_repo_history'),

    # GitHub: create a repository on the connected account, import one that
    # already exists, and read commits without needing a local clone.
    path('api/github/status', github_views.api_github_status, name='api_github_status'),
    path('api/github/create', github_views.api_github_create, name='api_github_create'),
    path('api/github/import', github_views.api_github_import, name='api_github_import'),
    path('api/repos/<int:pk>/github-delete', github_views.api_github_delete, name='api_github_delete'),
    path('api/repos/<int:pk>/commits', github_views.api_github_commits, name='api_github_commits'),
    path('api/repos/<int:pk>/documentation', github_views.api_repo_documentation, name='api_repo_documentation'),
    path('api/repos/<int:pk>/docs/save', github_views.api_repo_doc_save, name='api_repo_doc_save'),
    path('api/repos/<int:pk>/docs/import', github_views.api_repo_doc_import, name='api_repo_doc_import'),
    path('api/repos/<int:pk>/docs/<int:doc_id>/delete', github_views.api_repo_doc_delete, name='api_repo_doc_delete'),

    # Token-authenticated public API for external agents (see api_public.py).
    path('api/v1/whoami', public_api.whoami, name='public_whoami'),
    path('api/v1/activity', public_api.activity_feed, name='public_activity'),
    path('api/activity', github_views.api_activity, name='api_activity'),
    path('api/v1/tasks', public_api.tasks, name='public_tasks'),
    path('api/v1/tasks/<int:pk>', public_api.task_detail, name='public_task_detail'),

    path('api/client-requests', cr.api_client_requests, name='api_client_requests'),
    path('api/client-requests/create', cr.api_client_request_create, name='api_client_request_create'),
    path('api/client-requests/<int:pk>', cr.api_client_request_update, name='api_client_request_update'),
    path('api/client-requests/<int:pk>/send', cr.api_client_request_send, name='api_client_request_send'),
    path('api/client-requests/<int:pk>/delete', cr.api_client_request_delete, name='api_client_request_delete'),
    # No auth - the token in the URL is the authorisation.
    path('api/public/client-request/<str:token>', cr.public_client_request, name='public_client_request'),
    path('api/public/client-request/<str:token>/attach', cr.public_attach, name='public_attach'),
    path('api/public/client-request/<str:token>/attach/<int:pk>/delete', cr.public_attach_delete, name='public_attach_delete'),
    path('api/client-requests/attachments/<int:pk>/download', cr.attachment_download, name='attachment_download'),

    # The CargoWise report runs, which used to live in their own repository
    # behind their own systemd timer.
    # Projects as records rather than a string on a task: the Gantt, the
    # project detail, its history, and the reporting figures.
    # The weekly management report: eight sections, plus the records it needs
    # that the tracker never held - tickets, risks, SLAs, priorities, actions.
    # The Pricing Report: the CargoWise pricing export and the turnover
    # analysis rows appended under it, loaded into the database.
    path('api/pricing/report', pricing_api.api_pricing_report, name='api_pricing_report'),
    path('api/pricing/upload', pricing_api.api_pricing_upload, name='api_pricing_upload'),
    path('api/pricing/imports/<int:pk>/activate', pricing_api.api_pricing_activate, name='api_pricing_activate'),

    path('api/management/report', mgmt.api_management_report, name='api_management_report'),
    # The V3 template shape, which is the document management actually reads.
    path('api/management/up-report', mgmt.api_up_report, name='api_up_report'),
    path('api/management/up-dashboard', mgmt.api_up_dashboard, name='api_up_dashboard'),
    path('api/management/up-report.pdf', mgmt.api_up_report_pdf, name='api_up_report_pdf'),
    path('api/management/up-report/email', mgmt.api_up_report_email, name='api_up_report_email'),
    path('api/management/client-note', mgmt.api_client_note_save, name='api_client_note_save'),
    path('api/management/focus-matrix', mgmt.api_focus_matrix_save, name='api_focus_matrix_save'),
    path('api/management/header', mgmt.api_report_header_save, name='api_report_header_save'),
    path('api/management/save', mgmt.api_management_save, name='api_management_save'),
    path('api/management/chase', mgmt.api_management_chase, name='api_management_chase'),
    path('api/management/send', mgmt.api_management_send, name='api_management_send'),
    path('api/management/actions', mgmt.api_action_save, name='api_action_save'),
    path('api/management/actions/<int:pk>/delete', mgmt.api_action_delete, name='api_action_delete'),
    path('api/management/risks', mgmt.api_risk_save, name='api_risk_save'),
    path('api/management/tickets', mgmt.api_ticket_save, name='api_ticket_save'),
    path('api/management/focus', mgmt.api_focus_save, name='api_focus_save'),
    path('api/management/focus/<int:pk>/delete', mgmt.api_focus_delete, name='api_focus_delete'),
    path('api/management/agreements', mgmt.api_agreement_save, name='api_agreement_save'),

    path('api/projects', projects.api_projects, name='api_projects'),
    path('api/projects/gantt', projects.api_project_gantt, name='api_project_gantt'),
    path('api/projects/metrics', projects.api_project_metrics, name='api_project_metrics'),
    path('api/projects/<str:name>', projects.api_project_update, name='api_project_update'),
    path('api/projects/<str:name>/activity', projects.api_project_activity, name='api_project_activity'),

    path('api/awa/reports', awa.api_awa_reports, name='api_awa_reports'),
    path('api/awa/runs', awa.api_awa_runs, name='api_awa_runs'),
    path('api/awa/runs/<int:pk>', awa.api_awa_run_detail, name='api_awa_run_detail'),
    path('api/awa/run', awa.api_awa_run, name='api_awa_run'),

    path('api/sites', sites.api_sites, name='api_sites'),
    # The published sites themselves. nginx serves these in production; this
    # route is what makes a local preview show its images.
    path('sites/', sites.serve_site_file, name='site_root'),
    path('sites/<path:rest>', sites.serve_site_file, name='site_file'),
    path('api/sites/create', sites.api_site_create, name='api_site_create'),
    path('api/sites/<int:pk>', sites.api_site_update, name='api_site_update'),
    path('api/sites/<int:pk>/preview', sites.api_site_preview, name='api_site_preview'),
    path('api/sites/<int:pk>/publish', sites.api_site_publish, name='api_site_publish'),
    path('api/sites/<int:pk>/delete', sites.api_site_delete, name='api_site_delete'),
    path('api/sites/<int:pk>/blocks', sites.api_block_save, name='api_block_save'),
    path('api/sites/<int:pk>/blocks/reorder', sites.api_blocks_reorder, name='api_blocks_reorder'),
    path('api/sites/<int:pk>/blocks/<int:block>/delete', sites.api_block_delete, name='api_block_delete'),

    path('api/handbook', hb.api_handbook, name='api_handbook'),
    path('api/handbook/create', hb.api_handbook_save, name='api_handbook_create'),
    path('api/handbook/<int:pk>', hb.api_handbook_save, name='api_handbook_update'),
    path('api/handbook/<int:pk>/delete', hb.api_handbook_delete, name='api_handbook_delete'),
    path('api/handbook/server-access', hb.api_server_access, name='api_server_access'),
    path('api/handbook/server-access/<int:pk>/reveal', hb.api_server_secret, name='api_server_secret'),

    path('api/tasks', platform_api.api_planner_tasks, name='api_tasks'),
    path('api/tasks/projects', platform_api.api_task_projects, name='api_task_projects'),
    path('api/tasks/projects/create', platform_api.api_project_create, name='api_project_create'),
    path('api/tasks/projects/update', platform_api.api_project_update, name='api_project_update'),
    path('api/tasks/projects/delete', platform_api.api_project_delete, name='api_project_delete'),
    path('api/tasks/projects/move', platform_api.api_project_move, name='api_project_move'),
    path('api/tasks/lists/create', platform_api.api_list_create, name='api_list_create'),
    path('api/tasks/lists/delete', platform_api.api_list_delete, name='api_list_delete'),
    path('api/tasks/workspaces/members', wsa.api_workspace_members, name='api_workspace_members'),
    path('api/tasks/workspaces/members/add', wsa.api_workspace_member_add, name='api_workspace_member_add'),
    path('api/tasks/workspaces/members/remove', wsa.api_workspace_member_remove, name='api_workspace_member_remove'),
    path('api/tasks/my-access', wsa.api_my_access, name='api_my_access'),
    path('api/tasks/workspaces/save', platform_api.api_workspace_save, name='api_workspace_save'),
    path('api/tasks/workspaces/delete', platform_api.api_workspace_delete, name='api_workspace_delete'),
    path('api/tasks/create', platform_api.api_planner_task_create, name='api_task_create'),
    path('api/tasks/<int:pk>', platform_api.api_planner_task_update, name='api_task_update'),
    path('api/tasks/<int:pk>/delete', platform_api.api_planner_task_delete, name='api_task_delete'),
    path('api/tasks/<int:pk>/timer', platform_api.api_task_timer, name='api_task_timer'),


    path('', views.home, name='home'),
    path('api/tp-progress/', views.get_tp_progress, name='get_tp_progress'),
    path('monitor/', views.sync_monitor, name='sync_monitor'),
    path('monitor/api/', views.sync_monitor_api, name='sync_monitor_api'),
    path('monitor/sync-all/', views.sync_all, name='sync_all'),
    path('monitor/sync-all/status/', views.sync_all_status, name='sync_all_status'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # JSON auth API for the Sentinel frontend (no trailing slash — matches fetch paths)
    path('api/auth/login', views.api_login, name='api_login'),
    path('api/auth/logout', views.api_logout, name='api_logout'),
    path('api/auth/me', views.api_me, name='api_me'),
    path('api/dashboard/summary', views.api_dashboard_summary, name='api_dashboard_summary'),
    # User management + module access (Sentinel frontend)
    path('api/users', views.api_users, name='api_users'),
    path('api/users/create', views.api_user_create, name='api_user_create'),
    path('api/users/<int:pk>', views.api_user_update, name='api_user_update'),
    path('api/users/<int:pk>/delete', views.api_user_delete, name='api_user_delete'),
    path('api/servers', views.api_servers, name='api_servers'),
    path('api/servers/metrics', views.api_server_metrics, name='api_server_metrics'),
    path('api/servers/create', views.api_server_create, name='api_server_create'),
    path('api/servers/<int:pk>', views.api_server_update, name='api_server_update'),
    path('api/servers/<int:pk>/delete', views.api_server_delete, name='api_server_delete'),
    path('api/servers/<int:pk>/scan', views.api_server_scan, name='api_server_scan'),
    path('api/data-analysis/stations', views.api_data_analysis_stations, name='api_data_analysis_stations'),
    path('api/data-analysis/sync', views.api_station_sync, name='api_station_sync'),
    # Documentation: Company → System → Documents
    path('api/docs/companies', views.api_doc_companies, name='api_doc_companies'),
    path('api/docs/companies/<int:pk>', views.api_doc_company_detail, name='api_doc_company_detail'),
    path('api/docs/systems', views.api_doc_systems, name='api_doc_systems'),
    path('api/docs/systems/<int:pk>', views.api_doc_system_detail, name='api_doc_system_detail'),
    path('api/docs/contents', views.api_doc_contents, name='api_doc_contents'),
    path('api/docs/folders', views.api_doc_folders, name='api_doc_folders'),
    path('api/docs/folders/<int:pk>', views.api_doc_folder_detail, name='api_doc_folder_detail'),
    path('api/docs/documents', views.api_doc_documents, name='api_doc_documents'),
    path('api/docs/documents/<int:pk>', views.api_doc_document_detail, name='api_doc_document_detail'),
    path('api/docs/documents/<int:pk>/download', views.api_doc_download, name='api_doc_download'),
    path('turnover/', views.turnover, name='turnover'),
    path('pnl/', views.pnl, name='pnl'),
    path('atl/', views.atl, name='atl'),
    path('ccc/', views.ccc, name='ccc'),
    path('ccd/', views.ccd, name='ccd'),
    path('con/', views.con, name='con'),
    path('dor/', views.dor, name='dor'),
    path('fax/', views.fax, name='fax'),
    path('hec/', views.hec, name='hec'),
    path('hnl/', views.hnl, name='hnl'),
    path('hou/', views.hou, name='hou'),
    path('ics/', views.ics, name='ics'),
    path('imp/', views.imp, name='imp'),
    path('jfk/', views.jfk, name='jfk'),
    path('lax/', views.lax, name='lax'),
    path('lcl/', views.lcl, name='lcl'),
    path('ord/', views.ord, name='ord'),
    path('dfw/', views.dfw, name='dfw'),
    path('bravo-tran/', views.bravo_tran, name='bravo_tran'),
    path('bravo-tran/allocate/', views.bravo_tran_allocate, name='bravo_tran_allocate'),
    path('bravo-tran/deallocate/', views.bravo_tran_deallocate, name='bravo_tran_deallocate'),
    path('tfs/', views.tfs, name='tfs'),
    path('tfs/sync/', views.sync_tfs, name='sync_tfs'),
    path('tfs/sync/progress/', views.sync_tfs_progress, name='sync_tfs_progress'),
    path('ppg/', views.ppg, name='ppg'),
    path('creditor/', views.creditor, name='creditor'),
    path('condor-dor/', views.condor_dor, name='condor_dor'),
    path('condor-dor/sync/', views.sync_condor_dor, name='sync_condor_dor'),
    path('condor-dor/sync/progress/', views.sync_condor_dor_progress, name='sync_condor_dor_progress'),
    path('sync/', views.sync_data, name='sync_data'),
    path('sync/progress/', views.sync_progress, name='sync_progress'),
    path('ppg/sync/', views.sync_ppg, name='sync_ppg'),
    path('ppg/sync/progress/', views.sync_ppg_progress, name='sync_ppg_progress'),
    path('dor/sync/', views.sync_dor, name='sync_dor'),
    path('dor/sync/progress/', views.sync_dor_progress, name='sync_dor_progress'),
    path('con/sync/', views.sync_con, name='sync_con'),
    path('con/sync/progress/', views.sync_con_progress, name='sync_con_progress'),
    path('atl/sync/', views.sync_atl, name='sync_atl'),
    path('atl/sync/progress/', views.sync_atl_progress, name='sync_atl_progress'),
    path('hnl/sync/', views.sync_hnl, name='sync_hnl'),
    path('hnl/sync/progress/', views.sync_hnl_progress, name='sync_hnl_progress'),
    path('ccc/sync/', views.sync_ccc, name='sync_ccc'),
    path('ccc/sync/progress/', views.sync_ccc_progress, name='sync_ccc_progress'),
    path('ccd/sync/', views.sync_ccd, name='sync_ccd'),
    path('ccd/sync/progress/', views.sync_ccd_progress, name='sync_ccd_progress'),
    path('fax/sync/', views.sync_fax, name='sync_fax'),
    path('fax/sync/progress/', views.sync_fax_progress, name='sync_fax_progress'),
    path('hou/sync/', views.sync_hou, name='sync_hou'),
    path('hou/sync/progress/', views.sync_hou_progress, name='sync_hou_progress'),
    path('ics/sync/', views.sync_ics, name='sync_ics'),
    path('ics/sync/progress/', views.sync_ics_progress, name='sync_ics_progress'),
    path('imp/sync/', views.sync_imp, name='sync_imp'),
    path('imp/sync/progress/', views.sync_imp_progress, name='sync_imp_progress'),
    path('jfk/sync/', views.sync_jfk, name='sync_jfk'),
    path('jfk/sync/progress/', views.sync_jfk_progress, name='sync_jfk_progress'),
    path('lax/sync/', views.sync_lax, name='sync_lax'),
    path('lax/sync/progress/', views.sync_lax_progress, name='sync_lax_progress'),
    path('lcl/sync/', views.sync_lcl, name='sync_lcl'),
    path('lcl/sync/progress/', views.sync_lcl_progress, name='sync_lcl_progress'),
    path('ord/sync/', views.sync_ord, name='sync_ord'),
    path('ord/sync/progress/', views.sync_ord_progress, name='sync_ord_progress'),
    path('dfw/sync/', views.sync_dfw, name='sync_dfw'),
    path('dfw/sync/progress/', views.sync_dfw_progress, name='sync_dfw_progress'),
    path('import-ops/', views.import_ops, name='import_ops'),
    path('import-ops/sync/', views.sync_import_ops, name='sync_import_ops'),
    path('import-ops/sync/progress/', views.sync_import_ops_progress_view, name='sync_import_ops_progress'),
    path('data-analysis/', views.data_analysis, name='data_analysis'),
    path('wip-accrual/', views.wip_accrual, name='wip_accrual'),
    path('accruals/', views.accruals, name='accruals'),
    path('wip-accrual/sync/', views.sync_wip_accrual, name='sync_wip_accrual'),
    path('wip-accrual/sync/progress/', views.sync_wip_accrual_progress_view, name='sync_wip_accrual_progress'),
    path('updown-trader/', views.updown_trader, name='updown_trader'),
    path('updown-trader/sync/', views.sync_updown_trader, name='sync_updown_trader'),
    path('updown-trader/sync/progress/', views.sync_updown_trader_progress, name='sync_updown_trader_progress'),
    path('onedrive/auth/', views.onedrive_auth, name='onedrive_auth'),
    path('onedrive/callback/', views.onedrive_callback, name='onedrive_callback'),
    path('onedrive/check/', views.onedrive_check, name='onedrive_check'),
    path('powerbi/embed/', views.get_powerbi_embed, name='get_powerbi_embed'),
    path('powerbi/embed/save/', views.save_powerbi_embed, name='save_powerbi_embed'),
    path('users/', views.user_list, name='user_list'),
    path('users/add/', views.user_create, name='user_create'),
    path('users/<int:user_id>/edit/', views.user_edit, name='user_edit'),
    path('users/<int:user_id>/delete/', views.user_delete, name='user_delete'),
    path('settings/', views.settings_view, name='settings'),
    path('settings/save/', views.save_settings, name='save_settings'),
    path('useu-list/', views.useu_list, name='useu_list'),
    path('useu-list/update-cell/', views.useu_update_cell, name='useu_update_cell'),
    path('useu-list/add/', views.useu_create_contact, name='useu_create_contact'),
    path('useu-list/<int:contact_id>/edit/', views.useu_edit_contact, name='useu_edit_contact'),
    path('useu-list/<int:contact_id>/delete/', views.useu_delete_contact, name='useu_delete_contact'),
    path('useu-list/send-all/', views.send_all_touchpoint, name='send_all_touchpoint'),
    path('useu-list/send-all/progress/', views.send_all_progress, name='send_all_progress'),
    path('useu-list/send-all/stop/', views.stop_sending, name='stop_sending'),
    path('webhooks/ses/', views.ses_webhook, name='ses_webhook'),
    path('unsubscribe/<str:token>/', views.unsubscribe, name='unsubscribe'),
    path('email-templates/', views.email_templates, name='email_templates'),
    path('email-templates/save/', views.email_template_save, name='email_template_save'),
    path('email-templates/send/', views.send_touchpoint, name='send_touchpoint'),
    path('email-templates/send-test/', views.send_test_touchpoint, name='send_test_touchpoint'),
    path('email-templates/set-schedule/', views.set_touchpoint_schedule, name='set_touchpoint_schedule'),
    path('email-templates/get-schedules/', views.get_touchpoint_schedules, name='get_touchpoint_schedules'),
    path('reporting/', views.reporting, name='reporting'),
    path('planner/', views.planner, name='planner'),
    path('gantt/', views.gantt, name='gantt'),
    path('automations/', views.automations_panel, name='automations_panel'),
    path('automations/toggle/', views.automation_toggle, name='automation_toggle'),
    path('automations/stop-emails/', views.automation_stop_all_emails, name='automation_stop_all_emails'),

    # ── System testing (the Management Live Sheet, as a module) ──────────────
    path('api/system-testing/projects', st.api_test_projects, name='api_test_projects'),
    path('api/system-testing/projects/create', st.api_test_project_save, name='api_test_project_create'),
    path('api/system-testing/projects/<int:pk>', st.api_test_project_detail, name='api_test_project_detail'),
    path('api/system-testing/projects/<int:pk>/save', st.api_test_project_save, name='api_test_project_save'),
    path('api/system-testing/projects/<int:pk>/delete', st.api_test_project_delete, name='api_test_project_delete'),
    path('api/system-testing/projects/<int:pk>/duplicate', st.api_test_project_duplicate, name='api_test_project_duplicate'),
    path('api/system-testing/projects/<int:pk>/changes', st.api_test_changes, name='api_test_changes'),
    path('api/system-testing/projects/<int:pk>/export', st.api_test_export, name='api_test_export'),
    path('api/system-testing/projects/<int:pk>/export.pdf', st.api_test_export_pdf, name='api_test_export_pdf'),
    path('api/system-testing/import', st.api_test_import, name='api_test_import'),
    # Reviewer share links: owner side, then the token-only reviewer side.
    path('api/system-testing/projects/<int:pk>/share-links', st_share.api_share_links, name='api_share_links'),
    path('api/system-testing/projects/<int:pk>/share-links/create', st_share.api_share_link_create, name='api_share_link_create'),
    path('api/system-testing/share-links/<int:pk>/revoke', st_share.api_share_link_revoke, name='api_share_link_revoke'),
    path('api/public/readiness/<str:token>', st_share.public_readiness, name='public_readiness'),
    path('api/public/readiness/<str:token>/changes', st_share.public_readiness_changes, name='public_readiness_changes'),
    path('api/public/readiness/<str:token>/rows/<int:pk>', st_share.public_readiness_save, name='public_readiness_save'),
    path('api/system-testing/areas/create', st.api_test_area_save, name='api_test_area_create'),
    path('api/system-testing/areas/<int:pk>', st.api_test_area_save, name='api_test_area_save'),
    path('api/system-testing/areas/<int:pk>/delete', st.api_test_area_delete, name='api_test_area_delete'),
    path('api/system-testing/areas/<int:pk>/versions', st.api_test_version_create, name='api_test_version_create'),
    path('api/system-testing/versions/<int:pk>/delete', st.api_test_version_delete, name='api_test_version_delete'),
    path('api/system-testing/items/create', st.api_test_item_save, name='api_test_item_create'),
    path('api/system-testing/items/<int:pk>', st.api_test_item_save, name='api_test_item_save'),
    path('api/system-testing/items/<int:pk>/delete', st.api_test_item_delete, name='api_test_item_delete'),
    path('api/system-testing/items/<int:pk>/iterations', st.api_test_iteration_create, name='api_test_iteration_create'),
    path('api/system-testing/iterations/<int:pk>/delete', st.api_test_iteration_delete, name='api_test_iteration_delete'),
    path('api/system-testing/notes/create', st.api_test_note_save, name='api_test_note_create'),
    path('api/system-testing/notes/<int:pk>', st.api_test_note_save, name='api_test_note_save'),
    path('api/system-testing/notes/<int:pk>/delete', st.api_test_note_delete, name='api_test_note_delete'),
]
