# Generated by Django 6.0.2 on 2026-02-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TABLE IF EXISTS ppg_pnl CASCADE;

                CREATE TABLE ppg_pnl (
                    id SERIAL PRIMARY KEY,
                    job_number VARCHAR(50),
                    job_local_ref VARCHAR(50),
                    branch VARCHAR(10),
                    dept VARCHAR(10),
                    status VARCHAR(10),
                    rep VARCHAR(20),
                    ops VARCHAR(20),
                    job_profit NUMERIC(15, 2),
                    revenue NUMERIC(15, 2),
                    wip NUMERIC(15, 2),
                    cost NUMERIC(15, 2),
                    accrual NUMERIC(15, 2),
                    controlling_agent TEXT,
                    controlling_customer TEXT,
                    management_group TEXT,
                    debtor_sales_reps TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );

                CREATE INDEX idx_ppg_job_number ON ppg_pnl(job_number);
                CREATE INDEX idx_ppg_branch ON ppg_pnl(branch);
            """,
            reverse_sql="DROP TABLE IF EXISTS ppg_pnl CASCADE;"
        )
    ]
