# Generated by Django 6.0.2 on 2026-02-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_update_ppg_pnl_structure'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TABLE IF EXISTS ppg_pnl CASCADE;

                CREATE TABLE ppg_pnl (
                    id SERIAL PRIMARY KEY,
                    division VARCHAR(50),
                    account_name TEXT,
                    value NUMERIC(15, 2),
                    date INTEGER,
                    date_fixed DATE,
                    budget_actual VARCHAR(20),
                    week VARCHAR(20),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );

                CREATE INDEX idx_ppg_division ON ppg_pnl(division);
                CREATE INDEX idx_ppg_date ON ppg_pnl(date);
                CREATE INDEX idx_ppg_budget_actual ON ppg_pnl(budget_actual);
            """,
            reverse_sql="DROP TABLE IF EXISTS ppg_pnl CASCADE;"
        )
    ]
