# Generated by Django 5.2.11 on 2026-03-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_projecttask_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBIEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50, unique=True)),
                ('embed_url', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'powerbi_embed',
            },
        ),
    ]
