# Generated by Django 5.2.11 on 2026-03-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='USEUContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, default='', max_length=500)),
                ('default', models.CharField(blank=True, default='', max_length=10)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('attach', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('touchpoint_1', models.CharField(blank=True, default='', max_length=50)),
                ('tp1_sent_on', models.CharField(blank=True, default='', max_length=50)),
                ('touchpoint_2', models.CharField(blank=True, default='', max_length=50)),
                ('last_touch', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Faulty Data', 'Faulty Data')], default='Active', max_length=20)),
                ('tp1_processing_id', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'useu_contacts',
                'ordering': ['id'],
            },
        ),
    ]
