# Generated by Django 5.2.11 on 2026-03-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_useucontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouchpointTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touchpoint_number', models.IntegerField(unique=True)),
                ('subject', models.CharField(default='', max_length=500)),
                ('body', models.TextField(default='')),
                ('enabled', models.BooleanField(default=True)),
                ('days_after_previous', models.IntegerField(default=7, help_text='Days after previous touchpoint to send this one')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'touchpoint_templates',
                'ordering': ['touchpoint_number'],
            },
        ),
    ]
