# Generated by Django 5.2.11 on 2026-03-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_create_touchpoint_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touchpointtemplate',
            name='enabled',
        ),
        migrations.AddField(
            model_name='touchpointtemplate',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='touchpoint_attachments/'),
        ),
        migrations.AddField(
            model_name='touchpointtemplate',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
