# Generated by Django 5.2.11 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_update_useu_contacts_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchpointtemplate',
            name='body_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
