# Generated by Django 6.0.3 on 2026-03-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_add_deal_lost_reason'),
        ('dashboard', '0030_create_wip_accrual_table'),
    ]

    operations = [
    ]
