# Generated by Django 6.0.3 on 2026-04-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_fix_ccd_pnl_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(blank=True, default='', max_length=500)),
                ('shipment_direction', models.CharField(blank=True, default='', max_length=500)),
                ('report_date', models.CharField(blank=True, default='', max_length=500)),
                ('trans', models.CharField(blank=True, default='', max_length=500)),
                ('customs_info', models.CharField(blank=True, default='', max_length=500)),
                ('mode', models.CharField(blank=True, default='', max_length=500)),
                ('origin', models.CharField(blank=True, default='', max_length=500)),
                ('origin_country', models.CharField(blank=True, default='', max_length=500)),
                ('destination', models.CharField(blank=True, default='', max_length=500)),
                ('destination_country', models.CharField(blank=True, default='', max_length=500)),
                ('consignor_code', models.CharField(blank=True, default='', max_length=500)),
                ('consignor_name', models.CharField(blank=True, default='', max_length=500)),
                ('consignee_code', models.CharField(blank=True, default='', max_length=500)),
                ('consignee_name', models.CharField(blank=True, default='', max_length=500)),
                ('house_ref', models.CharField(blank=True, default='', max_length=500)),
                ('incoterm', models.CharField(blank=True, default='', max_length=500)),
                ('additional_terms', models.CharField(blank=True, default='', max_length=500)),
                ('ppd_ccx', models.CharField(blank=True, default='', max_length=500)),
                ('goods_description', models.CharField(blank=True, default='', max_length=500)),
                ('origin_etd', models.CharField(blank=True, default='', max_length=500)),
                ('destination_eta', models.CharField(blank=True, default='', max_length=500)),
                ('weight', models.CharField(blank=True, default='', max_length=500)),
                ('weight_unit', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'import_ops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WipAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=500)),
                ('branch', models.CharField(blank=True, default='', max_length=500)),
                ('dept', models.CharField(blank=True, default='', max_length=500)),
                ('charge_code', models.CharField(blank=True, default='', max_length=500)),
                ('job', models.CharField(blank=True, default='', max_length=500)),
                ('local_ref', models.CharField(blank=True, default='', max_length=500)),
                ('wip', models.CharField(blank=True, default='', max_length=500)),
                ('accrual', models.CharField(blank=True, default='', max_length=500)),
                ('net_total', models.CharField(blank=True, default='', max_length=500)),
                ('added', models.CharField(blank=True, default='', max_length=500)),
                ('age', models.CharField(blank=True, default='', max_length=500)),
                ('debtor_creditor', models.CharField(blank=True, default='', max_length=500)),
                ('stat', models.CharField(blank=True, default='', max_length=500)),
                ('job_branch', models.CharField(blank=True, default='', max_length=500)),
                ('controlling_agent', models.CharField(blank=True, default='', max_length=500)),
                ('controlling_customer', models.CharField(blank=True, default='', max_length=500)),
                ('management_group', models.CharField(blank=True, default='', max_length=500)),
                ('exp_group', models.CharField(blank=True, default='', max_length=500)),
                ('orig', models.CharField(blank=True, default='', max_length=500)),
                ('eta', models.CharField(blank=True, default='', max_length=500)),
                ('etd', models.CharField(blank=True, default='', max_length=500)),
                ('posted_by', models.CharField(blank=True, default='', max_length=500)),
                ('posted_by_fullname', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'wip_accrual',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='touchpointtemplate',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Fixed date to automatically send this touchpoint', null=True),
        ),
        migrations.AlterField(
            model_name='useucontact',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Undeliverable', 'Undeliverable'), ('Lost', 'Lost'), ('Move to HubSpot', 'Move to HubSpot')], default='Active', max_length=20),
        ),
    ]
