# Generated by Django 6.0.3 on 2026-04-14 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_importops_wipaccrual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.EmailField(max_length=254)),
                ('from_address', models.EmailField(blank=True, default='', max_length=254)),
                ('touchpoint_number', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('provider', models.CharField(choices=[('ses', 'AWS SES'), ('graph', 'Microsoft Graph'), ('dry_run', 'Dry Run')], default='ses', max_length=16)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('dry_run', 'Dry Run')], default='sent', max_length=16)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='dashboard.useucontact')),
            ],
            options={
                'db_table': 'email_send_log',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['to_address', 'sent_at'], name='email_send__to_addr_6366c6_idx')],
            },
        ),
    ]
