# Generated by Django 6.0.3 on 2026-04-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_useucontact_deal_lost_reason_emailsendlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchpointtemplate',
            name='signature_image',
            field=models.FileField(blank=True, help_text='Inline signature image (referenced via cid:signature_tpN).', null=True, upload_to='touchpoint_signatures/'),
        ),
    ]
