# Generated by Django 4.2.30 on 2026-08-10 19:51

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_touchpointtemplate_signature_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doc_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='dashboard.doccompany')),
            ],
            options={
                'db_table': 'doc_system',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DocDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to=dashboard.models._doc_upload_path)),
                ('size', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=150)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dashboard.docsystem')),
            ],
            options={
                'db_table': 'doc_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
