# Generated by Django 6.0.3 on 2026-04-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_useucontact_moved_to_hubspot_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='company',
            field=models.CharField(blank=True, choices=[('magnum_opus', 'Magnum Opus'), ('food_safety', 'Food Safety Agency'), ('eclick', 'Eclick'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
