# Generated by Django 4.2.30 on 2026-08-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_doccompany_useucontact_deal_lost_reason_docsystem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard.docfolder')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='dashboard.docsystem')),
            ],
            options={
                'db_table': 'doc_folder',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='docdocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.docfolder'),
        ),
    ]
