# Generated by Django 6.0.3 on 2026-04-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_add_task_company_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_automations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_data_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_emailing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_planner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_sync_monitor',
            field=models.BooleanField(default=False),
        ),
    ]
