# Generated by Django 4.2.30 on 2026-08-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_useucontact_deal_lost_reason_docfolder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=120)),
                ('group', models.CharField(blank=True, default='', max_length=120)),
                ('ip', models.CharField(blank=True, default='', max_length=100)),
                ('host', models.CharField(blank=True, default='', max_length=200)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, default='', max_length=200)),
                ('os', models.CharField(blank=True, default='', max_length=200)),
                ('provider', models.CharField(blank=True, default='', max_length=200)),
                ('cpu', models.CharField(blank=True, default='', max_length=200)),
                ('ram', models.CharField(blank=True, default='', max_length=200)),
                ('disk', models.CharField(blank=True, default='', max_length=300)),
                ('access', models.CharField(blank=True, default='', max_length=400)),
                ('netbird_ip', models.CharField(blank=True, default='', max_length=100)),
                ('lan_ip', models.CharField(blank=True, default='', max_length=100)),
                ('netbird_url', models.CharField(blank=True, default='', max_length=300)),
                ('ssh_user', models.CharField(blank=True, default='', max_length=100)),
                ('ssh_ip', models.CharField(blank=True, default='', max_length=100)),
                ('ssh_key', models.CharField(blank=True, default='', max_length=200)),
                ('runtimes', models.TextField(blank=True, default='')),
                ('services', models.TextField(blank=True, default='')),
                ('databases', models.TextField(blank=True, default='')),
                ('domains', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'server_record',
                'ordering': ['order', 'id'],
            },
        ),
    ]
