# Generated by Django 4.2.30 on 2026-08-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_serverrecord_useucontact_deal_lost_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrecord',
            name='password',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='serverrecord',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
