# Generated by Django 6.0.3 on 2026-04-21 12:31
#
# The deal_lost_reason column was actually added to the DB by an earlier ad-hoc change
# (migration 0035's name references it but the operation was missing). This migration
# only updates Django's state for that field, then alters the status choices.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_add_user_page_access'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='useucontact',
                    name='deal_lost_reason',
                    field=models.CharField(blank=True, default='', max_length=500),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='useucontact',
            name='status',
            field=models.CharField(
                choices=[
                    ('Active', 'Active'),
                    ('Inactive', 'Inactive'),
                    ('Undeliverable', 'Undeliverable'),
                    ('Lost', 'Lost'),
                    ('Move to HubSpot', 'Move to HubSpot'),
                ],
                default='Active',
                max_length=20,
            ),
        ),
    ]
