# Generated by Django 4.2.30 on 2026-04-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_useucontact_deal_lost_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useucontact',
            name='opted_out_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
