# Generated by Django 4.2.30 on 2026-08-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_serverrecord_password_serverrecord_scanned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_automations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_data_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_emailing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_planner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_sync_monitor',
            field=models.BooleanField(default=False),
        ),
    ]
