# Generated by Django 4.2.30 on 2026-08-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_userprofile_can_automations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doccompany',
            name='brand_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='doccompany',
            name='contact_email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='doccompany',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='doccompany',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='doccompany',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doccompany',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='doccompany',
            name='logo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doccompany',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
