# Generated by Django 4.2.30 on 2026-08-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_doccompany_brand_color_doccompany_contact_email_and_more'),
    ]

    operations = [
        # NOTE: makemigrations also wants to AddField useucontact.deal_lost_reason
        # here, but that column already exists in the database (migration state has
        # drifted from the schema — the same op recurs in 0037/0038/0039). Applying
        # it would fail with "column already exists", so it is deliberately left
        # out: this migration only creates the two new platform tables.
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('local_path', models.CharField(blank=True, default='', max_length=500)),
                ('remote_url', models.CharField(blank=True, default='', max_length=500)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('azure', 'Azure DevOps'), ('other', 'Other')], default='github', max_length=20)),
                ('default_branch', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='dashboard.serverrecord')),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'db_table': 'repository_record',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True)),
                ('company', models.CharField(blank=True, default='', max_length=120)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('internal', 'Internal'), ('other', 'Other')], default='production', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('parked', 'Parked'), ('redirect', 'Redirect'), ('transferring', 'Transferring'), ('expired', 'Expired')], default='active', max_length=20)),
                ('registrar', models.CharField(blank=True, default='', max_length=200)),
                ('dns_provider', models.CharField(blank=True, default='', max_length=200)),
                ('nameservers', models.TextField(blank=True, default='')),
                ('primary_url', models.CharField(blank=True, default='', max_length=400)),
                ('registered_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('ssl_expires_on', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_records', to='dashboard.serverrecord')),
            ],
            options={
                'db_table': 'domain_record',
                'ordering': ['order', 'name'],
            },
        ),
    ]
