# Generated by Django 4.2.30 on 2026-09-02 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0047_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('software', 'Software'), ('website', 'Website'), ('project', 'Project'), ('general', 'General')], default='project', max_length=20)),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('intro', models.TextField(blank=True, default='', help_text='Short note shown above the questions.')),
                ('questions', models.JSONField(default=list)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('answered', 'Answered')], default='draft', max_length=20)),
                ('notify_email', models.EmailField(blank=True, default='', help_text='Where the completed answers are sent. Defaults to the creator.', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
