# Generated by Django 4.2.30 on 2026-09-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_clientrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
