# Generated by Django 4.2.30 on 2026-09-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_projecttask_actual_hours_projecttask_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='cc_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='kind_other',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='list_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='kind',
            field=models.CharField(choices=[('software', 'Software'), ('website', 'Website'), ('reports', 'Reports'), ('project', 'Project'), ('other', 'Other')], default='project', max_length=20),
        ),
    ]
