# Generated by Django 4.2.30 on 2026-09-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_clientrequest_cc_emails_clientrequest_kind_other_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_meta',
                'ordering': ['order', 'name'],
            },
        ),
    ]
