# Generated by Django 4.2.30 on 2026-09-02 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_projectlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='dashboard.workspace'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='projectlist',
            unique_together={('project_name', 'workspace', 'name')},
        ),
    ]
