# Generated by Django 4.2.30 on 2026-09-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_alter_projectlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmeta',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='workspace',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='workspace',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
