# Generated by Django 4.2.30 on 2026-09-02 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0056_workspacemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandbookArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('getting_started', 'Getting started'), ('access', 'Access & accounts'), ('rules', 'Rules & expectations'), ('how_to', 'How-to guides'), ('systems', 'Systems & architecture'), ('other', 'Other')], default='getting_started', max_length=32)),
                ('summary', models.CharField(blank=True, default='', help_text='One line shown in the list, before anyone opens it.', max_length=300)),
                ('body', models.TextField(blank=True, default='', help_text='Plain text. Blank lines separate paragraphs; "- " starts a bullet.')),
                ('is_pinned', models.BooleanField(default=False)),
                ('for_new_starters', models.BooleanField(default=False, help_text='Include in the checklist a new joiner is handed.')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbook_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'handbook_article',
                'ordering': ['-is_pinned', 'order', 'title'],
            },
        ),
    ]
