# Generated by Django 4.2.30 on 2026-09-02 14:20

import dashboard.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_handbookarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('file', 'File'), ('link', 'Link')], max_length=8)),
                ('question', models.CharField(blank=True, default='', max_length=500)),
                ('label', models.CharField(blank=True, default='', max_length=300)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ethan\\OneDrive\\Desktop\\American World Wide Agencies\\Software\\Workspace\\MagnumOpus-Automation-Hub\\automations\\private_media\\client-uploads'), upload_to=dashboard.models._client_upload_path)),
                ('original_name', models.CharField(blank=True, default='', max_length=300)),
                ('size', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.clientrequest')),
            ],
            options={
                'db_table': 'client_request_attachment',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
