# Generated by Django 4.2.30 on 2026-09-02 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0058_clientrequestattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('site_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=300)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('palette', models.CharField(choices=[('slate', 'Slate — professional, cool grey'), ('ocean', 'Ocean — blue, corporate'), ('forest', 'Forest — green, calm'), ('sunset', 'Sunset — warm orange'), ('plum', 'Plum — purple, creative'), ('mono', 'Mono — black and white')], default='slate', max_length=20)),
                ('font', models.CharField(choices=[('modern', 'Modern — Inter'), ('classic', 'Classic — Playfair + Source Sans'), ('technical', 'Technical — IBM Plex'), ('friendly', 'Friendly — Poppins + Karla')], default='modern', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_url', models.URLField(blank=True, default='', max_length=500)),
                ('published_ip', models.CharField(blank=True, default='', max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_sites', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='dashboard.clientrequest')),
            ],
            options={
                'db_table': 'client_site',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hero', 'Hero'), ('about', 'About'), ('services', 'Services'), ('features', 'Features'), ('gallery', 'Gallery'), ('testimonial', 'Testimonial'), ('stats', 'Numbers'), ('pricing', 'Pricing'), ('cta', 'Call to action'), ('contact', 'Contact'), ('text', 'Text')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='dashboard.clientsite')),
            ],
            options={
                'db_table': 'site_block',
                'ordering': ['order', 'id'],
            },
        ),
    ]
