# Generated by Django 4.2.30 on 2026-09-08 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0061_awa_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmeta',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='client',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='client_contact',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='quoted_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('in_progress_guidance', 'In Progress (Guidance Required)'), ('completed_review_pending', 'Completed (Review Pending)'), ('completed_discrepancy', 'Completed (Data Discrepancy Addressing)'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planned', max_length=32),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='development_status',
            field=models.CharField(blank=True, choices=[('original_quoted', 'Original / Quoted Development'), ('new_development', 'New Development'), ('new_development_qms', 'New Development - QMS must be involved'), ('new_development_qms_change', 'New Development - QMS Change'), ('new_quoted_development', 'New Development / Quoted Development'), ('ongoing_development', 'Ongoing Development')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_progress_guidance', 'In Progress (Guidance Required)'), ('review', 'Review'), ('review_pending', 'Completed (Review Pending)'), ('discrepancy', 'Completed (Data Discrepancy Addressing)'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='backlog', max_length=20),
        ),
        migrations.CreateModel(
            name='SentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('general', 'General report'), ('project', 'Project report'), ('client', 'Client report'), ('weekly', 'Weekly report'), ('complete', 'Complete report')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('recipients', models.TextField(blank=True, default='', help_text='Comma-separated addresses')),
                ('custom_message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('project_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('partial', 'Partially sent'), ('failed', 'Failed')], default='sent', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sent_report',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_admin_response', models.BooleanField(default=False)),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dashboard.taskcomment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.projecttask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_comment',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='task_commen_task_id_dd5a62_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('kind', models.CharField(choices=[('created', 'Created'), ('status', 'Status changed'), ('priority', 'Priority changed'), ('assigned', 'Assignment changed'), ('dates', 'Dates changed'), ('hours', 'Hours changed'), ('development', 'Development type changed'), ('comment', 'Comment added'), ('edited', 'Edited'), ('deleted', 'Deleted'), ('report', 'Report sent')], max_length=20)),
                ('field', models.CharField(blank=True, default='', max_length=40)),
                ('old_value', models.CharField(blank=True, default='', max_length=300)),
                ('new_value', models.CharField(blank=True, default='', max_length=300)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='dashboard.projecttask')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_name', '-created_at'], name='task_activi_project_34b98c_idx')],
            },
        ),
    ]
