# Generated by Django 4.2.30 on 2026-09-08 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0063_management_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementreport',
            name='developed_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='managementreport',
            name='issue_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='managementreport',
            name='morale_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='managementreport',
            name='report_version',
            field=models.CharField(blank=True, default='V3', max_length=10),
        ),
        migrations.AddField(
            model_name='managementreport',
            name='staff_morale',
            field=models.CharField(blank=True, choices=[('depleted', 'Depleted'), ('inefficient', 'Inefficient'), ('cruising', 'Cruising'), ('momentum', 'Maintaining Momentum'), ('visionary', 'Pro-Active & Visionary Mindset')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='sprint',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='stream',
            field=models.CharField(blank=True, choices=[('web', 'WEB'), ('app', 'APP'), ('api', 'API'), ('support', 'Support'), ('internal', 'Internal / Admin')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='riskitem',
            name='resolution_time',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='hosting_capacity',
            field=models.CharField(blank=True, default='', help_text='e.g. 4 vCPU / 8 GB, 62% used', max_length=120),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='is_reconciled',
            field=models.BooleanField(default=False, help_text='Management only'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='next_deliverable',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='next_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyfocus',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CompanyFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('bucket', models.CharField(max_length=200)),
                ('split_goal_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('support_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'company_focus',
                'ordering': ['week_start', 'order', 'bucket'],
                'unique_together': {('week_start', 'bucket')},
            },
        ),
        migrations.CreateModel(
            name='StaffFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('bucket', models.CharField(help_text='Client name, or an internal bucket', max_length=200)),
                ('planned_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_focus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_focus',
                'ordering': ['week_start', 'bucket'],
                'unique_together': {('week_start', 'person', 'bucket')},
            },
        ),
        migrations.CreateModel(
            name='ClientWeekNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('client', models.CharField(max_length=200)),
                ('sprint', models.CharField(blank=True, default='', max_length=80)),
                ('project_due_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('last_report_update', models.DateField(blank=True, null=True)),
                ('next_week_note', models.TextField(blank=True, default='')),
                ('next_week_due', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('next_week_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_week_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_week_note',
                'ordering': ['week_start', 'order', 'client'],
                'unique_together': {('week_start', 'client')},
            },
        ),
    ]
