# Generated by Django 4.2.30 on 2026-09-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_template_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmeta',
            name='is_automated',
            field=models.BooleanField(default=False, help_text='Automated or operational work, not client delivery'),
        ),
    ]
