# Generated by Django 4.2.30 on 2026-09-10 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0065_exclude_automated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=400)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_modified', models.DateTimeField(blank=True, null=True)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('quote_rows', models.IntegerField(default=0)),
                ('turnover_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='The load the report reads. Only one is active at a time.')),
                ('loaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pricing_import',
                'ordering': ['-loaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('quote', 'Pricing quote'), ('turnover', 'Turnover analysis')], default='quote', max_length=10)),
                ('row_number', models.IntegerField(default=0, help_text='Row in the source sheet, for tracing a figure back.')),
                ('client', models.CharField(blank=True, default='', max_length=60)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('branch', models.CharField(blank=True, default='', max_length=40)),
                ('month_label', models.CharField(blank=True, default='', max_length=30)),
                ('month_start', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.CharField(blank=True, default='', max_length=4)),
                ('month_sort', models.IntegerField(blank=True, null=True)),
                ('quote_no', models.BigIntegerField(blank=True, null=True)),
                ('booking_no', models.CharField(blank=True, default='', max_length=60)),
                ('quote_status', models.TextField(blank=True, default='')),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('booked', models.DateTimeField(blank=True, null=True)),
                ('conversion_days', models.FloatField(blank=True, null=True)),
                ('converted', models.BooleanField(default=False)),
                ('missed_opportunity', models.BooleanField(default=False)),
                ('transport_mode', models.CharField(blank=True, default='', max_length=20)),
                ('mode', models.CharField(blank=True, default='', max_length=20)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('weight_unit', models.CharField(blank=True, default='', max_length=8)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('volume_unit', models.CharField(blank=True, default='', max_length=8)),
                ('chargeable', models.FloatField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, default='', max_length=20)),
                ('destination', models.CharField(blank=True, default='', max_length=20)),
                ('origin_country', models.CharField(blank=True, default='', max_length=8)),
                ('destination_country', models.CharField(blank=True, default='', max_length=8)),
                ('incoterm', models.CharField(blank=True, default='', max_length=20)),
                ('direction', models.CharField(blank=True, default='', help_text='Import, Export or Domestic.', max_length=12)),
                ('au_nz_row', models.CharField(blank=True, default='', help_text='AU/NZ or ROW, by destination.', max_length=8)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=20)),
                ('assigned_to_name', models.CharField(blank=True, default='', max_length=120)),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('duplicate_flag', models.CharField(blank=True, default='', help_text='Unique or Duplicate.', max_length=12)),
                ('duplicate_pickup', models.IntegerField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='dashboard.pricingimport')),
            ],
            options={
                'db_table': 'pricing_row',
                'indexes': [models.Index(fields=['source', 'block'], name='pricing_row_source__41c9c1_idx'), models.Index(fields=['source', 'month_start'], name='pricing_row_source__e44c78_idx'), models.Index(fields=['source', 'branch'], name='pricing_row_source__aea67a_idx'), models.Index(fields=['source', 'client'], name='pricing_row_source__b10cc5_idx')],
            },
        ),
    ]
