# Generated by Django 4.2.30 on 2026-09-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_pricing_view_converted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, help_text='When the running timer was started. Null means not running.', null=True),
        ),
    ]
