# Generated by Django 4.2.30 on 2026-09-11 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0070_task_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text="Identifier within the repo, e.g. 'docs/02-the-data-model.md'", max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='', help_text='Markdown')),
                ('order', models.IntegerField(default=0)),
                ('updated_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='dashboard.repository')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repo_docs_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repository_doc',
                'ordering': ['order', 'path'],
                'unique_together': {('repository', 'path')},
            },
        ),
    ]
