# Generated by Django 4.2.30 on 2026-09-11 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0071_repodoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('verb', models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('completed', 'completed'), ('reopened', 'reopened'), ('deleted', 'deleted'), ('sent', 'sent'), ('imported', 'imported')], max_length=20)),
                ('object_type', models.CharField(help_text='task, repository, document, list, …', max_length=40)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_label', models.CharField(blank=True, default='', max_length=300)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('project', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('web', 'In the platform'), ('api', 'Through the API'), ('system', 'Automatic')], default='web', max_length=10)),
                ('via', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activity',
                'db_table': 'activity_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_en_created_7a2893_idx'), models.Index(fields=['actor', '-created_at'], name='activity_en_actor_i_d31716_idx'), models.Index(fields=['object_type', 'object_id'], name='activity_en_object__54e6d5_idx')],
            },
        ),
    ]
