# Generated by Django 4.2.30 on 2026-09-22 05:27

import dashboard.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0072_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequestattachment',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\MagnumOpus-Automation-Hub\\automations\\private_media\\client-uploads'), upload_to=dashboard.models._client_upload_path),
        ),
        migrations.CreateModel(
            name='TestProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('client', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.TextField(blank=True, default='', help_text='The blurb at the top of the pack, explaining what it covers.')),
                ('testing_window', models.CharField(blank=True, default='', help_text='Free text, e.g. "14 - 18 September".', max_length=120)),
                ('version_label', models.CharField(blank=True, default='', help_text='Build under test, e.g. "Inspector App Version 2.1.5".', max_length=120)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_project',
                'ordering': ['is_archived', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dashboard.testproject')),
            ],
            options={
                'db_table': 'test_note',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='dashboard.testproject')),
            ],
            options={
                'db_table': 'test_area',
                'ordering': ['order', 'id'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, default='', help_text='Testing day the item was raised, e.g. "Day 1".', max_length=40)),
                ('issue', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('bucket', models.CharField(choices=[('in_scope_change', 'In Scope Change'), ('change_request', 'Change Request'), ('new_development', 'New Development'), ('developer_enhancement', 'Developer Enhancements')], default='in_scope_change', max_length=32)),
                ('dev_status', models.CharField(choices=[('in_progress', 'In Progress'), ('done_internally_tested', 'Done & Internally Tested'), ('requires_clarification', 'Requires Clarification'), ('rectified_requires_testing', 'Rectified & Requires Testing')], default='in_progress', max_length=32)),
                ('tested', models.CharField(choices=[('tested', 'Tested'), ('not_tested', 'Not Tested')], default='not_tested', max_length=16)),
                ('readiness', models.CharField(choices=[('pass', 'PASS'), ('requires_action', 'REQUIRES ACTION'), ('outstanding', 'OUTSTANDING')], default='requires_action', max_length=20)),
                ('client_feedback', models.TextField(blank=True, default='', help_text='The client-side column, e.g. "Live review: PASS".')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.testarea')),
            ],
            options={
                'db_table': 'test_item',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['area', 'readiness'], name='test_item_area_id_ede6b8_idx'), models.Index(fields=['area', 'dev_status'], name='test_item_area_id_c5f217_idx')],
            },
        ),
    ]
