# Generated by Django 4.2.30 on 2026-09-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_alter_clientrequestattachment_file_testproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testarea',
            name='version_label',
            field=models.CharField(blank=True, default='', help_text='Build under test for this app, e.g. "Version 2.1.8".', max_length=160),
        ),
    ]
