# Generated by Django 4.2.30 on 2026-09-22 06:13
#
# Hand-ordered: the auto-generated version dropped TestArea.version_label before
# TestVersion existed, which would have thrown away every version already
# recorded. The table is created first, the labels are copied across, and only
# then is the old column removed.

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    """Carry each area's single label across as its first released version."""
    TestArea = apps.get_model('dashboard', 'TestArea')
    TestVersion = apps.get_model('dashboard', 'TestVersion')
    rows = []
    for area in TestArea.objects.exclude(version_label='').exclude(
            version_label=None):
        rows.append(TestVersion(area=area, label=area.version_label[:80], order=0))
    if rows:
        TestVersion.objects.bulk_create(rows)


def backward(apps, schema_editor):
    """Fold the chain back to one label, keeping the build most recently released."""
    TestArea = apps.get_model('dashboard', 'TestArea')
    for area in TestArea.objects.all():
        last = area.versions.order_by('order', 'id').last()
        if last:
            area.version_label = last.label[:160]
            area.save(update_fields=['version_label'])


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_testarea_version_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "2.1.8".', max_length=80)),
                ('note', models.CharField(blank=True, default='', help_text='What this build changed, if it is worth recording.', max_length=300)),
                ('released_on', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dashboard.testarea')),
            ],
            options={
                'db_table': 'test_version',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(forward, backward),
        migrations.RemoveField(
            model_name='testarea',
            name='version_label',
        ),
        migrations.AlterField(
            model_name='testarea',
            name='name',
            field=models.CharField(help_text='Named for the system being tested, e.g. "Inspector App".', max_length=120),
        ),
    ]
