# Generated by Django 4.2.30 on 2026-09-22 07:15
#
# Hand-ordered: the auto-generated version dropped the verdict columns off
# TestItem before TestIteration had been populated from them, which would have
# discarded every result already recorded. The table and its foreign keys are
# created first, each item's existing verdict is copied across as iteration 1,
# and only then are the old columns removed.

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    """Each existing item becomes an item with one completed pass."""
    TestItem = apps.get_model('dashboard', 'TestItem')
    TestIteration = apps.get_model('dashboard', 'TestIteration')
    rows = [
        TestIteration(
            item=item,
            number=1,
            dev_status=item.dev_status,
            tested=item.tested,
            readiness=item.readiness,
            client_feedback=item.client_feedback,
        )
        for item in TestItem.objects.all()
    ]
    if rows:
        TestIteration.objects.bulk_create(rows)


def backward(apps, schema_editor):
    """Fold the passes back onto the item, keeping the latest verdict."""
    TestItem = apps.get_model('dashboard', 'TestItem')
    for item in TestItem.objects.all():
        last = item.iterations.order_by('number', 'id').last()
        if last:
            item.dev_status = last.dev_status
            item.tested = last.tested
            item.readiness = last.readiness
            item.client_feedback = last.client_feedback
            item.save(update_fields=[
                'dev_status', 'tested', 'readiness', 'client_feedback'])


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_test_version_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, help_text='1 for the first test.')),
                ('dev_status', models.CharField(choices=[('in_progress', 'In Progress'), ('done_internally_tested', 'Done & Internally Tested'), ('requires_clarification', 'Requires Clarification'), ('rectified_requires_testing', 'Rectified & Requires Testing')], default='in_progress', max_length=32)),
                ('tested', models.CharField(choices=[('tested', 'Tested'), ('not_tested', 'Not Tested')], default='not_tested', max_length=16)),
                ('readiness', models.CharField(choices=[('pass', 'PASS'), ('requires_action', 'REQUIRES ACTION'), ('outstanding', 'OUTSTANDING')], default='requires_action', max_length=20)),
                ('client_feedback', models.TextField(blank=True, default='', help_text='The client-side column, e.g. "Live review: PASS".')),
                ('tested_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'test_iteration',
                'ordering': ['number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='testiteration',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='dashboard.testitem'),
        ),
        migrations.AddField(
            model_name='testiteration',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iterations', to='dashboard.testversion'),
        ),
        migrations.AddIndex(
            model_name='testiteration',
            index=models.Index(fields=['item', 'number'], name='test_iterat_item_id_e439e4_idx'),
        ),

        # Only now is it safe to drop the originals.
        migrations.RunPython(forward, backward),

        migrations.RemoveIndex(
            model_name='testitem',
            name='test_item_area_id_ede6b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='testitem',
            name='test_item_area_id_c5f217_idx',
        ),
        migrations.RemoveField(
            model_name='testitem',
            name='client_feedback',
        ),
        migrations.RemoveField(
            model_name='testitem',
            name='dev_status',
        ),
        migrations.RemoveField(
            model_name='testitem',
            name='readiness',
        ),
        migrations.RemoveField(
            model_name='testitem',
            name='tested',
        ),
    ]
