# Generated by Django 4.2.30 on 2026-09-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_test_share_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='testproject',
            name='window_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testproject',
            name='window_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testproject',
            name='testing_window',
            field=models.CharField(blank=True, default='', help_text='As written on an imported pack, e.g. "14 - 18 September".', max_length=120),
        ),
    ]
