# Generated by Django 4.2.30 on 2026-09-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_testing_window_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testitem',
            name='day',
        ),
    ]
