# Generated by Django 4.2.30 on 2026-09-23 19:37

import dashboard.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_drop_item_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveConsignmentImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=400)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_modified', models.DateTimeField(blank=True, null=True)),
                ('export_timestamp', models.DateTimeField(blank=True, null=True)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'receive_consignment_import',
                'ordering': ['-export_timestamp', '-loaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='clientrequestattachment',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Ethan\\Desktop\\Magnum Opus Software\\Source Code\\Workspace\\automations\\private_media\\client-uploads'), upload_to=dashboard.models._client_upload_path),
        ),
        migrations.CreateModel(
            name='ReceiveConsignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_consignment_id', models.CharField(db_index=True, max_length=60)),
                ('rcn_reference', models.CharField(blank=True, default='', max_length=60)),
                ('next_open_service', models.CharField(blank=True, default='', max_length=120)),
                ('consignor', models.TextField(blank=True, default='')),
                ('consignee', models.TextField(blank=True, default='')),
                ('booking_party', models.TextField(blank=True, default='')),
                ('number_of_packages', models.IntegerField(default=0)),
                ('bkd', models.IntegerField(default=0, verbose_name='Booked')),
                ('arv', models.IntegerField(default=0, verbose_name='Arrived')),
                ('ctt', models.IntegerField(default=0, verbose_name='Counted')),
                ('pic', models.IntegerField(default=0, verbose_name='Picked')),
                ('put', models.IntegerField(default=0, verbose_name='Put away')),
                ('in_warehouse', models.IntegerField(default=0)),
                ('overs', models.IntegerField(default=0)),
                ('warehouse', models.CharField(blank=True, default='', max_length=120)),
                ('service_level', models.CharField(blank=True, default='', max_length=120)),
                ('next_discharge_port', models.CharField(blank=True, default='', max_length=120)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('consignor_name', models.CharField(blank=True, default='', max_length=200)),
                ('consignor_country', models.CharField(blank=True, default='', max_length=80)),
                ('booking_party_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_unbooked', models.BooleanField(db_index=True, default=False)),
                ('has_overs', models.BooleanField(default=False)),
                ('has_consignee', models.BooleanField(default=False)),
                ('has_discharge_port', models.BooleanField(default=False)),
                ('has_next_open_service', models.BooleanField(default=False)),
                ('age_days', models.IntegerField(blank=True, null=True)),
                ('age_bucket', models.CharField(blank=True, default='', max_length=20)),
                ('age_bucket_order', models.IntegerField(default=99)),
                ('source_file', models.CharField(blank=True, default='', max_length=400)),
                ('export_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_latest_snapshot', models.BooleanField(db_index=True, default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='dashboard.receiveconsignmentimport')),
            ],
            options={
                'db_table': 'receive_consignment',
                'ordering': ['-age_days', 'receive_consignment_id'],
                'indexes': [models.Index(fields=['is_unbooked', 'in_warehouse'], name='rc_unbooked_inwhse_idx'), models.Index(fields=['is_latest_snapshot'], name='rc_latest_idx')],
            },
        ),
    ]
