# Generated by Django 4.2.30 on 2026-09-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_receiveconsignmentimport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveconsignment',
            name='booking_party_country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='receiveconsignment',
            name='completion_date_only',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='receiveconsignment',
            name='consignee_country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='receiveconsignment',
            name='consignee_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='receiveconsignment',
            name='file_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiveconsignment',
            name='row_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=480),
        ),
        migrations.AddField(
            model_name='receiveconsignment',
            name='service_level_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='receiveconsignment',
            name='service_level_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='receiveconsignment',
            name='warehouse_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='receiveconsignment',
            name='warehouse_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
