# Generated by Django 4.2.30 on 2026-09-25 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_receiveconsignment_booking_party_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unfiled_tasks', to='dashboard.workspace'),
        ),
    ]
