# Generated by Django 4.2.30 on 2026-10-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_pricing_view_not_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchPod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(db_index=True, max_length=10)),
                ('load_list', models.CharField(max_length=40, unique=True)),
                ('reference', models.CharField(blank=True, default='', max_length=60)),
                ('consol', models.CharField(blank=True, default='', max_length=40)),
                ('master_bill', models.CharField(blank=True, default='', max_length=60)),
                ('carrier_code', models.CharField(blank=True, default='', max_length=40)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_discharge_port', models.CharField(blank=True, default='', max_length=10)),
                ('transport_mode', models.CharField(blank=True, default='', max_length=10)),
                ('cto_cutoff', models.DateTimeField(blank=True, null=True)),
                ('dtu_count', models.IntegerField(default=0)),
                ('dtus', models.CharField(blank=True, default='', max_length=400)),
                ('vehicles', models.CharField(blank=True, default='', max_length=400)),
                ('dispatched_at', models.DateTimeField(db_index=True)),
                ('pod_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('pod_uploaded_by', models.CharField(blank=True, default='', max_length=20)),
                ('pod_count', models.IntegerField(default=0)),
                ('hours_to_pod', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('hours_waiting', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('status', models.CharField(db_index=True, max_length=10)),
                ('status_order', models.IntegerField(default=99)),
                ('kpi_met', models.BooleanField(blank=True, null=True)),
                ('needs_action', models.BooleanField(db_index=True, default=False)),
                ('dispatched_date', models.DateField(db_index=True)),
                ('dispatched_local', models.CharField(blank=True, default='', max_length=16)),
                ('pod_uploaded_local', models.CharField(blank=True, default='', max_length=16)),
                ('pulled_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dispatch_pod',
                'ordering': ['status_order', 'dispatched_at'],
            },
        ),
    ]
