# Generated by Django 4.2.30 on 2026-10-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_dispatch_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchpod',
            name='booking_party',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='dispatchpod',
            name='in_awa_view',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
