# Generated by Django 4.2.30 on 2026-10-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_dispatch_pod_awa_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmeta',
            name='demo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='hosting',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='tech_stack',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='website_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='website_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='repository',
            name='project_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
