# Generated by Django 4.2.30 on 2026-10-03 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0088_project_website_and_repos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(help_text='Hostname and Proxmox VM name', max_length=63)),
                ('vmid', models.IntegerField(blank=True, null=True)),
                ('os', models.CharField(blank=True, default='', max_length=80)),
                ('cores', models.IntegerField(default=2)),
                ('memory_mb', models.IntegerField(default=4096)),
                ('disk_gb', models.IntegerField(default=100)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('username', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('provisioning', 'Setting up'), ('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='queued', max_length=20)),
                ('step', models.CharField(blank=True, default='', max_length=120)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_server',
                'ordering': ['-created_at'],
            },
        ),
    ]
