# Generated by Django 4.2.30 on 2026-10-03 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0089_project_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_index=True, max_length=100)),
                ('kind', models.CharField(choices=[('database', 'Database'), ('server', 'Server login'), ('website', 'Website admin'), ('api', 'API key'), ('email', 'Email account'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('secret_encrypted', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='dashboard.projectserver')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_credential',
                'ordering': ['kind', 'label'],
            },
        ),
    ]
