# Generated by Django 4.2.30 on 2026-10-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_project_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('kind', models.CharField(blank=True, default='', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='', help_text='Markdown')),
                ('files', models.JSONField(blank=True, default=list)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, default='commit', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_docs', to='dashboard.repository')),
            ],
            options={
                'db_table': 'commit_doc',
                'ordering': ['-committed_at'],
                'unique_together': {('repository', 'sha')},
            },
        ),
    ]
