# Generated by Django 4.2.30 on 2026-10-03 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def carry_over_logged_hours(apps, schema_editor):
    """Hours typed in before time tracking become one entry per task, so no
    task's total changes when actual_hours starts being worked out from entries."""
    ProjectTask = apps.get_model('dashboard', 'ProjectTask')
    TimeEntry = apps.get_model('dashboard', 'TimeEntry')
    for t in ProjectTask.objects.filter(actual_hours__gt=0):
        when = t.updated_at or t.created_at
        TimeEntry.objects.create(
            task=t, user=None, user_name='Before time tracking', started_at=when, ended_at=when,
            seconds=int(round(float(t.actual_hours) * 3600)),
            note='Logged before time tracking', source='manual')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0092_server_access_and_console_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=150)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('seconds', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('source', models.CharField(choices=[('timer', 'Timer'), ('manual', 'Added by hand')], default='timer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='dashboard.projecttask')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'time_entry',
                'ordering': ['-started_at'],
            },
        ),
        migrations.RunPython(carry_over_logged_hours, migrations.RunPython.noop),
    ]
