# Generated by Django 4.2.30 on 2026-10-03 15:59

import dashboard.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0093_time_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_index=True, max_length=100)),
                ('kind', models.CharField(choices=[('problem', "Something's wrong"), ('change', 'Change request'), ('idea', 'Suggestion'), ('question', 'Question')], default='problem', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('area', models.CharField(blank=True, default='', help_text='Which screen or part of the system', max_length=200)),
                ('submitter_name', models.CharField(blank=True, default='', max_length=150)),
                ('submitter_email', models.EmailField(blank=True, default='', max_length=254)),
                ('submitter_role', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('planned', 'Planned'), ('done', 'Done'), ('declined', 'Declined')], default='new', max_length=20)),
                ('manager_note', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('form', 'Feedback form'), ('staff', 'Added by staff')], default='form', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='dashboard.projecttask')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_link',
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Ethan\\Desktop\\Magnum Opus Software\\Source Code\\Workspace\\automations\\private_media\\feedback'), upload_to=dashboard.models._feedback_upload_path)),
                ('original_name', models.CharField(blank=True, default='', max_length=300)),
                ('content_type', models.CharField(default='image/png', max_length=50)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.feedback')),
            ],
            options={
                'db_table': 'feedback_attachment',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
