# Generated by Django 4.2.30 on 2026-10-05 10:25

from django.db import migrations, models


# makemigrations also wants to rewrite the `file` fields on
# ClientRequestAttachment and FeedbackAttachment on every run, because their
# FileSystemStorage(location=...) serialises as an absolute path - here that is
# "D:\MagnumOpus-Automation-Hub\...", which would be baked into the migration
# and would not exist on the Linux server or on anybody else's machine. Those
# two operations are deliberately left out; the drift is in the model, not here.


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0094_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmeta',
            name='clickup_list_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='clickup_list_name',
            field=models.CharField(blank=True, default='', help_text='Shown in the UI so the link reads as a place, not an id.', max_length=200),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='clickup_dirty',
            field=models.BooleanField(db_index=True, default=False, help_text='Changed since the last successful push.'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='clickup_error',
            field=models.TextField(blank=True, default='', help_text='Why the last push failed, cleared when one succeeds.'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='clickup_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='clickup_task_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The task this mirrors in ClickUp. Empty means never pushed.', max_length=40),
        ),
    ]
