# Generated by Django 4.2.30 on 2026-10-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_clickup_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchLoadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(db_index=True, max_length=10)),
                ('load_list', models.CharField(max_length=40, unique=True)),
                ('reference', models.CharField(blank=True, default='', max_length=60)),
                ('master_bill', models.CharField(blank=True, default='', max_length=120)),
                ('booking_party', models.CharField(blank=True, default='', max_length=400)),
                ('last_discharge_port', models.CharField(blank=True, default='', max_length=10)),
                ('in_external_view', models.BooleanField(db_index=True, default=False)),
                ('in_awa_view', models.BooleanField(db_index=True, default=False)),
                ('unit_types', models.CharField(blank=True, default='', max_length=100)),
                ('vehicles', models.CharField(blank=True, default='', max_length=400)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('weight_unit', models.CharField(blank=True, default='', max_length=10)),
                ('total_volume', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('volume_unit', models.CharField(blank=True, default='', max_length=10)),
                ('packages', models.IntegerField(default=0)),
                ('staged_packages', models.IntegerField(default=0)),
                ('loaded_packages', models.IntegerField(default=0)),
                ('cto_cutoff', models.DateTimeField(blank=True, null=True)),
                ('cto_cutoff_local', models.CharField(blank=True, default='', max_length=16)),
                ('cto_cutoff_date', models.DateField(blank=True, db_index=True, null=True)),
                ('cutoff_today', models.BooleanField(db_index=True, default=False)),
                ('pulled_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dispatch_load_list',
                'ordering': ['-load_list'],
            },
        ),
    ]
