# Generated by Django 4.2.30 on 2026-10-07 10:24

from django.db import migrations, models


# The two attachment FileField rewrites makemigrations keeps proposing are left
# out again: their storage serialises as this machine's absolute path, which
# would not exist on the server. See 0095.


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_clickup_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clickup_user_id',
            field=models.CharField(blank=True, default='', help_text='ClickUp member id. Set it when email matching cannot.', max_length=20),
        ),
    ]
