# Generated by Django 4.2.30 on 2026-10-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_dispatch_load_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchloadlist',
            name='dep_packages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispatchloadlist',
            name='flo_packages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispatchloadlist',
            name='in_warehouse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispatchloadlist',
            name='load_list_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
