# Generated by Django 4.2.30 on 2026-10-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_clickup_user_mapping'),
        ('dashboard', '0097_dispatch_load_list_packages'),
    ]

    operations = [
    ]
